use_frameworks!

platform :ios, '11.0'
target 'E3db_Example' do
    pod 'E3db', :path => '../'

    target 'E3db_Tests' do
        inherit! :search_paths
        pod 'E3db', :path => '../'
        pod 'ResponseDetective', '~> 1.2'
        pod 'SwiftCheck', '~> 0.12'
        end
end
