use_frameworks!

platform :ios, 9.0
target 'E3db_Example' do
  pod 'E3db', :path => '../'
  pod 'E3db/Logging', :path => '../'

  target 'E3db_Tests' do
    inherit! :search_paths
    pod 'E3db', :path => '../'
    pod 'E3db/Logging', :path => '../'
    
    pod 'SwiftCheck', '~> 0.9'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
